/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food.management.system;

import Codes.User;
import Data.UserData;

/**
 *
 * @author Anushan Dharmarathna
 */
public class Signup extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        btnSignup.setEnabled(false);
    }

    public void Clear() {
        textName.setText("");
        textEmail.setText("");
        textMNumber.setText("");
        textPassword.setText("");
        btnClear.setEnabled(false);
    }

    public void validateFields() {
        String name = textName.getText();
        String email = textEmail.getText();
        String mobileNumber = textMNumber.getText();
        String password = textPassword.getText();
        if (!name.equals("") && email.matches(emailPattern) && mobileNumber.matches(mobileNumberPattern) && mobileNumber.length() == 10 && !password.equals("")) {
            btnSignup.setEnabled(true);
        } else {
            btnSignup.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textMNumber = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLoginCA = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FoodManagement = new javax.swing.JLabel();
        System = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(85, 40));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Create an account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        textName.setBackground(java.awt.SystemColor.controlHighlight);
        textName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        textName.setForeground(new java.awt.Color(0, 0, 0));
        textName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNameKeyReleased(evt);
            }
        });
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 300, -1));

        textEmail.setBackground(java.awt.SystemColor.controlHighlight);
        textEmail.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        textEmail.setForeground(new java.awt.Color(0, 0, 0));
        textEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textEmailKeyReleased(evt);
            }
        });
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 300, -1));

        textMNumber.setBackground(java.awt.SystemColor.controlHighlight);
        textMNumber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        textMNumber.setForeground(new java.awt.Color(0, 0, 0));
        textMNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textMNumberKeyReleased(evt);
            }
        });
        getContentPane().add(textMNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 300, -1));

        textPassword.setBackground(java.awt.SystemColor.controlHighlight);
        textPassword.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        textPassword.setForeground(new java.awt.Color(0, 0, 0));
        textPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 300, -1));

        btnSignup.setBackground(new java.awt.Color(51, 102, 255));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btnSignup.setText("Sign Up");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, -1, -1));

        btnClear.setBackground(new java.awt.Color(51, 102, 255));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, -1, -1));

        btnLoginCA.setBackground(new java.awt.Color(51, 102, 255));
        btnLoginCA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLoginCA.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        btnLoginCA.setText("Login");
        btnLoginCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCAActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Already have an account?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, -1, -1));

        FoodManagement.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        FoodManagement.setForeground(new java.awt.Color(0, 0, 0));
        FoodManagement.setText("Food Management");
        getContentPane().add(FoodManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        System.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        System.setForeground(new java.awt.Color(0, 0, 0));
        System.setText("System");
        getContentPane().add(System, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(244, 79, 90));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FirstPage.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setName(textName.getText());
        user.setEmail(textEmail.getText());
        user.setMobileNumber(textMNumber.getText());
        user.setPassword(textPassword.getText());
        UserData.save(user);
        Clear();

    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void textNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_textNameKeyReleased

    private void textEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_textEmailKeyReleased

    private void textMNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMNumberKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_textMNumberKeyReleased

    private void textPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPasswordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_textPasswordKeyReleased

    private void btnLoginCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCAActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLoginCAActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodManagement;
    private javax.swing.JLabel System;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLoginCA;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textMNumber;
    private javax.swing.JTextField textName;
    private javax.swing.JPasswordField textPassword;
    // End of variables declaration//GEN-END:variables
}
